# Generated by Django 3.2.9 on 2021-12-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='country',
            new_name='department',
        ),
    ]
